version: 2

sources:
  - name: staging
    database: silicon-mile-412319
    schema: weather_data

    tables:
      - name: forecast_data
      - name: airline_lookup
      - name: routes_lookup

models:
  - name: stg_airline_data
    description: ""
    columns:
      - name: airline_id
        data_type: int64
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn      

      - name: airline_name
        data_type: string
        description: ""

      - name: iata_code
        data_type: string
        description: ""

      - name: icao_code
        data_type: string
        description: ""

      - name: callsign
        data_type: string
        description: ""

      - name: country
        data_type: string
        description: ""

      - name: active
        data_type: string
        description: ""

  - name: stg_routes_data
    description: ""
    columns:
      - name: iata_code
        data_type: string
        description: ""

      - name: airline_id
        data_type: string
        description: ""

      - name: source_airport_iata
        data_type: string
        description: ""

      - name: source_airport_id
        data_type: string
        description: ""

      - name: destination_airport_iata
        data_type: string
        description: ""

      - name: destination_airport_id
        data_type: string
        description: ""

      - name: codeshare
        data_type: string
        description: ""

      - name: stops
        data_type: int64
        description: ""

      - name: equipment
        data_type: string
        description: ""

  - name: stg_forecast_data
    description: ""
    columns:
      - name: id
        data_type: string
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
          
      - name: location
        data_type: string
        description: ""

      - name: time_utc
        data_type: timestamp
        description: ""

      - name: time_utc_local
        data_type: timestamp
        description: ""

      - name: cloudbase
        data_type: numeric
        description: ""

      - name: cloudceiling
        data_type: numeric
        description: ""

      - name: cloudcover
        data_type: numeric
        description: ""

      - name: dewpoint
        data_type: numeric
        description: ""

      - name: evapotranspiration
        data_type: numeric
        description: ""

      - name: freezingrainintensity
        data_type: numeric
        description: ""

      - name: humidity
        data_type: numeric
        description: ""

      - name: iceaccumulation
        data_type: numeric
        description: ""

      - name: iceaccumulationlwe
        data_type: numeric
        description: ""

      - name: precipitationprobability
        data_type: numeric
        description: ""

      - name: pressuresurfacelevel
        data_type: numeric
        description: ""

      - name: rainaccumulation
        data_type: numeric
        description: ""

      - name: rainaccumulationlwe
        data_type: numeric
        description: ""

      - name: rainintensity
        data_type: numeric
        description: ""

      - name: sleetaccumulation
        data_type: numeric
        description: ""

      - name: sleetaccumulationlwe
        data_type: numeric
        description: ""

      - name: sleetintensity
        data_type: numeric
        description: ""

      - name: snowaccumulation
        data_type: numeric
        description: ""

      - name: snowaccumulationlwe
        data_type: numeric
        description: ""

      - name: snowdepth
        data_type: numeric
        description: ""

      - name: snowintensity
        data_type: numeric
        description: ""

      - name: temperature
        data_type: numeric
        description: ""

      - name: temperatureapparent
        data_type: numeric
        description: ""

      - name: uvhealthconcern
        data_type: numeric
        description: ""

      - name: uvhealthconcern_strength
        data_type: string
        description: ""

      - name: uvindex
        data_type: numeric
        description: ""

      - name: uvindex_strength
        data_type: string
        description: ""

      - name: visibility
        data_type: numeric
        description: ""

      - name: weathercode
        data_type: numeric
        description: ""

      - name: winddirection
        data_type: numeric
        description: ""

      - name: windgust
        data_type: numeric
        description: ""

      - name: windspeed
        data_type: numeric
        description: ""

      - name: insert_dt
        data_type: timestamp
        description: ""
